# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CS333_Final_Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        python -m unittest -v Test_TodoList.py
        python -m unittest -v Test_Task.py

    - name: Build Docker image
      run: |
        docker build -t python-image .

      #to build, use docker run -i python-image

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag python-image ${{ secrets.DOCKER_HUB_USERNAME }}/python-image:latest
        docker push $DOCKER_HUB_USERNAME/python-image:latest

    - name: Publish Docker image to GitHub Packages
      run: |
        echo "$DOCKER_HUB_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_HUB_USERNAME" --password-stdin
        docker pull $DOCKER_HUB_USERNAME/python-image:latest
        docker tag $DOCKER_HUB_USERNAME/python-image:latest docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}:latest
        docker push docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}:latest